### ISSUE TITLE
Invalid domain names generated

### ISSUE THREAD

**Issue by jezen** [fakedata-haskell/fakedata#52]
The [`Faker.Company.fixupName`][0] function used in generating domain names replaces spaces with underscores.

This is invalid according to [RFC 1035][1].

> The labels must follow the rules for ARPANET host names.  They must
start with a letter, end with a letter or digit, and **have as interior
characters only letters, digits, and hyphen**.  There are also some
restrictions on the length.  Labels must be 63 characters or less.

[0]: https://github.com/fakedata-haskell/fakedata/blob/master/src/Faker/Company.hs#L90-L98
[1]: https://datatracker.ietf.org/doc/html/rfc1035#section-2.3.1

**Comment by psibi** [comment]
I would be happy to accept a PR.

**Comment by jezen** [comment]
@psibi Here you are: https://github.com/fakedata-haskell/fakedata/pull/53.

**Comment by psibi** [comment]
New version has been released, closing the issue.
